version: "3"

services:

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    volumes:
      - db-data:/data
    networks:
      - database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  api:
    build:
      dockerfile: ./docker/web/Dockerfile
      context: ./
    ports:
      - 7000:7000
    networks:
      - database
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2

networks:
  database:

volumes:
  db-data: